/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedComercianteRouteImport } from './routes/_authenticated/comerciante'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComercianteRoute =
  AuthenticatedComercianteRouteImport.update({
    id: '/comerciante',
    path: '/comerciante',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/comerciante': typeof AuthenticatedComercianteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/comerciante': typeof AuthenticatedComercianteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/cliente': typeof AuthenticatedClienteRoute
  '/_authenticated/comerciante': typeof AuthenticatedComercianteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/explorar'
    | '/recuperar-senha'
    | '/cliente'
    | '/comerciante'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/explorar'
    | '/recuperar-senha'
    | '/cliente'
    | '/comerciante'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/explorar'
    | '/recuperar-senha'
    | '/_authenticated/cliente'
    | '/_authenticated/comerciante'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  ExplorarRoute: typeof ExplorarRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comerciante': {
      id: '/_authenticated/comerciante'
      path: '/comerciante'
      fullPath: '/comerciante'
      preLoaderRoute: typeof AuthenticatedComercianteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRoute
  AuthenticatedComercianteRoute: typeof AuthenticatedComercianteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClienteRoute: AuthenticatedClienteRoute,
  AuthenticatedComercianteRoute: AuthenticatedComercianteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  ExplorarRoute: ExplorarRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
